export const actionTypes = {
    FETCH_APARTAMENTS_SUCCESS: 'FETCH_APARTAMENTS_SUCCES',
    FETCH_APARTAMENTS_REQUEST: 'FETCH_APARTAMENTS_REQUEST',
    FETCH_APARTAMENTS_FAILURE: 'FETCH_APARTAMENTS_FAILURE',

    UPDATE_APARTAMENT: 'UPDATE_APARTAMENT'
};